#!/usr/bin/env bash
#install nginx
apt-get udpate
apt-get install -y nginx

#create directory where our pages will be stored
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/etc/nginx/html
	index	index.html index.htm;
    	server_name _;
    
    	location /redirect_me/ {
        	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    	}
"> /etc/nginx/sites-available/default

#reload nginx
service nginx restart
