#!/usr/bin/env bash
#print hour and minutes
hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minutes=1
	while [ $minutes -lt 60 ]
	do
		echo "$minutes"
		minutes=$((minutes + 1))
	done
	hour=$((hour + 1))
done
